=== richardman1/Facturatiesysteem/FacturatieSysteem/XML/ClientFormat.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Clienten">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Client" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ClientGegevens">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Naam"/>
                    <xs:element type="xs:string" name="Adres"/>
                    <xs:element type="xs:string" name="Postcode"/>
                    <xs:element type="xs:string" name="Woonplaats"/>
                    <xs:element type="xs:string" name="Geboortedatum"/>
                    <xs:element type="xs:string" name="Telefoonnummer"/>
                    <xs:element type="xs:string" name="Email"/>
                    <xs:element type="xs:string" name="BetaalMethode"/>
                    <xs:element type="xs:string" name="ResterendEigenRisico"/>
                    <xs:element type="xs:string" name="Rekeningnummer"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="VerzekeringPolissen">
              	<xs:complexType>
              		<xs:sequence>
		              	<xs:element name="VerzekeringPolis" maxOccurs="unbounded" minOccurs="0">
		                	<xs:complexType>
		                  		<xs:sequence>
		                    	 <xs:element type="xs:string" name="VerzekeringType"/>
			                     <xs:element type="xs:float" name="EigenRisico"/>
			                     <xs:element type="xs:string" name="startDatum"/>
			                     <xs:element type="xs:string" name="eindDatum"/>
			                  	</xs:sequence>
			                <xs:attribute type="xs:string" name="PolisNummer"/>
			                </xs:complexType>
			            </xs:element>
	              	</xs:sequence>
	            </xs:complexType>
	          </xs:element>
			  
              <xs:element name="Facturen">
              	<xs:complexType>
              		<xs:sequence>
		              	<xs:element name="Factuur" maxOccurs="unbounded" minOccurs="0">
		                	<xs:complexType>
		                  		<xs:sequence>
		                    	 <xs:element type="xs:string" name="FactuurDatum"/>
			                     <xs:element type="xs:string" name="VervalDatum"/>
								 <xs:element name="FactuurBehandelingen" maxOccurs="unbounded" minOccurs="0">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="FactuurBehandeling" maxOccurs="unbounded" minOccurs="0">
												<xs:complexType>
													<xs:sequence>
														<xs:element type="xs:string" name="BehandelafspraakID" maxOccurs="unbounded" minOccurs="0"/>
													</xs:sequence>
												<xs:attribute type="xs:string" name="BehandelingID"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								 </xs:element>
			                    <xs:element type="xs:float" name="TevergoedenBedrag"/>
								<xs:element type="xs:string" name="Status"/>
								<xs:element type="xs:float" name="Totaalprijs"/>
			                  	</xs:sequence>
			                <xs:attribute type="xs:string" name="FactuurNummer"/>
			                </xs:complexType>
			            </xs:element>
	              	</xs:sequence>
	            </xs:complexType>
	          </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:int" name="BSN"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== richardman1/Facturatiesysteem/FacturatieSysteem/XML/ClientFormat.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Clienten xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ClientFormat.xsd">

	
	<Client BSN="125651202">
		<ClientGegevens>
			<Naam>Sander Blijlevens</Naam>
			<Adres>Schijfstraat 26B</Adres>
			<Postcode>4847SM</Postcode>
			<Woonplaats>Teteringen                                                  </Woonplaats>
			<Geboortedatum>31-12-1995</Geboortedatum>
			<Telefoonnummer>0625235100</Telefoonnummer>
			<Email>sjmblijl@avans.nl</Email>
			<BetaalMethode>incasso</BetaalMethode>
			<ResterendEigenRisico>0.0</ResterendEigenRisico>
			<Rekeningnummer>NL47RABO0136052185</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="KJ8JUY">
				<VerzekeringType>CGZ-Basic</VerzekeringType>
				<EigenRisico>200.0</EigenRisico>
				<startDatum>01-01-2013</startDatum>
				<eindDatum>31-12-2013</eindDatum>
			</VerzekeringPolis>
			
			<VerzekeringPolis PolisNummer="BJOWB2">
				<VerzekeringType>CGZ-All-risk</VerzekeringType>
				<EigenRisico>250.0</EigenRisico>
				<startDatum>01-01-2015</startDatum>
				<eindDatum>01-01-2016</eindDatum>
			</VerzekeringPolis>
			<VerzekeringPolis PolisNummer="0GUNC4">
				<VerzekeringType>CGZ-All-risk</VerzekeringType>
				<EigenRisico>250.0</EigenRisico>
				<startDatum>03-11-2014</startDatum>
				<eindDatum>05-12-2015</eindDatum>
			</VerzekeringPolis>
			
			<VerzekeringPolis PolisNummer="123456">
				<VerzekeringType>CGZ-Basic</VerzekeringType>
				<EigenRisico>1125.48</EigenRisico>
				<startDatum>01-01-2010</startDatum>
				<eindDatum>31-12-2011</eindDatum>
			</VerzekeringPolis></VerzekeringPolissen>
		<Facturen><Factuur FactuurNummer="1"><FactuurDatum>06-11-2014</FactuurDatum><VervalDatum>20-11-2014</VervalDatum><FactuurBehandelingen><FactuurBehandeling BehandelingID="2349"><BehandelafspraakID>3498</BehandelafspraakID></FactuurBehandeling><FactuurBehandeling BehandelingID="6845"><BehandelafspraakID>684</BehandelafspraakID></FactuurBehandeling><FactuurBehandeling BehandelingID="9856"><BehandelafspraakID>3654</BehandelafspraakID></FactuurBehandeling><FactuurBehandeling BehandelingID="4745"><BehandelafspraakID>6798</BehandelafspraakID></FactuurBehandeling></FactuurBehandelingen><TevergoedenBedrag>240.0</TevergoedenBedrag><Status>Niet betaald</Status><Totaalprijs>55.0</Totaalprijs></Factuur></Facturen>
	</Client>

	<Client BSN="287496358">
		<ClientGegevens>
			<Naam>Jan de Wit</Naam>
			<Adres>wilhelmuslaan 12</Adres>
			<Postcode>8287BE</Postcode>
			<Woonplaats>Rotterdam</Woonplaats>
			<Geboortedatum>15-03-1980</Geboortedatum>
			<Telefoonnummer>0678297159</Telefoonnummer>
			<Email>j.d.w@gmail.com</Email>
			<BetaalMethode>Acceptgiro</BetaalMethode>
			<ResterendEigenRisico>285.0</ResterendEigenRisico>
			<Rekeningnummer>78NLINGB0789134835168</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="DD8NCN">
				<VerzekeringType>CGZ-All-risk</VerzekeringType>
				<EigenRisico>285.0</EigenRisico>
				<startDatum>06-11-2014</startDatum>
				<eindDatum>06-11-2015</eindDatum>
			</VerzekeringPolis>
		</VerzekeringPolissen>
		<Facturen/>
		<Behandelingen/>
		<Diagnoses/>
	</Client>

	<Client BSN="715976842">
		<ClientGegevens>
			<Naam>Ricardo Jobse</Naam>
			<Adres>Sterrenkroos 192</Adres>
			<Postcode>4823ME</Postcode>
			<Woonplaats>Breda</Woonplaats>
			<Geboortedatum>17-10-1994</Geboortedatum>
			<Telefoonnummer>0646193003</Telefoonnummer>
			<Email>jobse.ricardo@gmail.com</Email>
			<BetaalMethode>Incasso</BetaalMethode>
			<ResterendEigenRisico>200.0</ResterendEigenRisico>
			<Rekeningnummer>28 nl ingb 45678645</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="WVLJIT">
				<VerzekeringType>CGZ-Basic</VerzekeringType>
				<EigenRisico>200.0</EigenRisico>
				<startDatum>03-02-2012</startDatum>
				<eindDatum>03-02-2015</eindDatum>
			</VerzekeringPolis>
		</VerzekeringPolissen>
		<Facturen/>
		<Behandelingen/>
		<Diagnoses/>
	</Client>

	<Client BSN="755488689">
		<ClientGegevens>
			<Naam>Richard de Jongh</Naam>
			<Adres>rapherbahn 24</Adres>
			<Postcode>7895CC</Postcode>
			<Woonplaats>Tilburg</Woonplaats>
			<Geboortedatum>23-06-1995</Geboortedatum>
			<Telefoonnummer>0679856881</Telefoonnummer>
			<Email>r.d.j@gmail.com</Email>
			<BetaalMethode>Incasso</BetaalMethode>
			<ResterendEigenRisico>285.0</ResterendEigenRisico>
			<Rekeningnummer>89abna9872347</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="4AY22B">
				<VerzekeringType>CGZ-All-risk</VerzekeringType>
				<EigenRisico>285.0</EigenRisico>
				<startDatum>17-09-2000</startDatum>
				<eindDatum>17-09-2020</eindDatum>
			</VerzekeringPolis>
		</VerzekeringPolissen>
		<Facturen/>
		<Behandelingen/>
		<Diagnoses/>
	</Client>

	<Client BSN="459862357">
		<ClientGegevens>
			<Naam>Carolina Jobse Montfulleda</Naam>
			<Adres>Sterrenkroos 192</Adres>
			<Postcode>4823ME</Postcode>
			<Woonplaats>Breda</Woonplaats>
			<Geboortedatum>23-05-1966</Geboortedatum>
			<Telefoonnummer>0612869148</Telefoonnummer>
			<Email>montfulleda@live.nl</Email>
			<BetaalMethode>Incasso</BetaalMethode>
			<ResterendEigenRisico>200.0</ResterendEigenRisico>
			<Rekeningnummer>19nlingb123456789</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="F8QM0N">
				<VerzekeringType>CGZ-Basic</VerzekeringType>
				<EigenRisico>200.0</EigenRisico>
				<startDatum>08-08-1980</startDatum>
				<eindDatum>08-08-2015</eindDatum>
			</VerzekeringPolis>
		</VerzekeringPolissen>
		<Facturen/>
		<Behandelingen/>
		<Diagnoses/>
	</Client>

	<Client BSN="985587269">
		<ClientGegevens>
			<Naam>Laura Jobse</Naam>
			<Adres>Sterrenkroos 192</Adres>
			<Postcode>4823ME</Postcode>
			<Woonplaats>Breda</Woonplaats>
			<Geboortedatum>31-03-1997</Geboortedatum>
			<Telefoonnummer>0648159784</Telefoonnummer>
			<Email>laura_jobse@live.nl</Email>
			<BetaalMethode>Incasso</BetaalMethode>
			<ResterendEigenRisico>200.0</ResterendEigenRisico>
			<Rekeningnummer>48NLINGB123789456</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="ZYL8CH">
				<VerzekeringType>CGZ-All-risk</VerzekeringType>
				<EigenRisico>200.0</EigenRisico>
				<startDatum>05-04-2002</startDatum>
				<eindDatum>05-04-2022</eindDatum>
			</VerzekeringPolis>
		</VerzekeringPolissen>
		<Facturen/>
		<Behandelingen/>
		<Diagnoses/>
	</Client>

	<Client BSN="134679852">
		<ClientGegevens>
			<Naam>Henk Jobse</Naam>
			<Adres>Sterrenkroos 192</Adres>
			<Postcode>4823ME</Postcode>
			<Woonplaats>Breda</Woonplaats>
			<Geboortedatum>10-04-1960</Geboortedatum>
			<Telefoonnummer>0643083076</Telefoonnummer>
			<Email>haha.jobse@casema.nl</Email>
			<BetaalMethode>Incasso</BetaalMethode>
			<ResterendEigenRisico>285.0</ResterendEigenRisico>
			<Rekeningnummer>97NLINGB123587946</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="CL5GL3">
				<VerzekeringType>CGZ-Basic</VerzekeringType>
				<EigenRisico>285.0</EigenRisico>
				<startDatum>05-05-2000</startDatum>
				<eindDatum>05-05-2030</eindDatum>
			</VerzekeringPolis>
		</VerzekeringPolissen>
		<Facturen/>
		<Behandelingen/>
		<Diagnoses/>
	</Client>

	<Client BSN="159784525">
		<ClientGegevens>
			<Naam>Alex de Vogel</Naam>
			<Adres>marialaan 12a</Adres>
			<Postcode>4844PJ</Postcode>
			<Woonplaats>Breda</Woonplaats>
			<Geboortedatum>25-09-1990</Geboortedatum>
			<Telefoonnummer>0648965781</Telefoonnummer>
			<Email>avogel@avans.nl</Email>
			<BetaalMethode>Acceptgiro</BetaalMethode>
			<ResterendEigenRisico>285.0</ResterendEigenRisico>
			<Rekeningnummer>57rabo12654896</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="WZZBOC">
				<VerzekeringType>CGZ-All-risk</VerzekeringType>
				<EigenRisico>285.0</EigenRisico>
				<startDatum>01-01-2000</startDatum>
				<eindDatum>01-01-2050</eindDatum>
			</VerzekeringPolis>
		</VerzekeringPolissen>
		<Facturen/>
		<Behandelingen/>
		<Diagnoses/>
	</Client>

	<Client BSN="215987684">
		<ClientGegevens>
			<Naam>Ilse Gerreman-Taalman</Naam>
			<Adres>Jan Pieterszoon Coenlaan 1</Adres>
			<Postcode>4562AJ</Postcode>
			<Woonplaats>Hulst</Woonplaats>
			<Geboortedatum>14-02-1964</Geboortedatum>
			<Telefoonnummer>0694311468</Telefoonnummer>
			<Email>ilse@gerreman.nl</Email>
			<BetaalMethode>Incasso</BetaalMethode>
			<ResterendEigenRisico>200.0</ResterendEigenRisico>
			<Rekeningnummer>NL02SNSB0259876354</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="7AQKKV">
				<VerzekeringType>CGZ-All-risk</VerzekeringType>
				<EigenRisico>200.0</EigenRisico>
				<startDatum>01-25-2014</startDatum>
				<eindDatum>01-25-2015</eindDatum>
			</VerzekeringPolis>
		</VerzekeringPolissen>
		<Facturen/>
		<Behandelingen/>
		<Diagnoses/>
	</Client>

	<Client BSN="093587698">
		<ClientGegevens>
			<Naam>Marinus Gerreman</Naam>
			<Adres>Jan Pieterszoon Coenlaan 1</Adres>
			<Postcode>4562AJ</Postcode>
			<Woonplaats>Hulst</Woonplaats>
			<Geboortedatum>31-05-1962</Geboortedatum>
			<Telefoonnummer>0694877654</Telefoonnummer>
			<Email>rini@gerreman.nl</Email>
			<BetaalMethode>Incasso</BetaalMethode>
			<ResterendEigenRisico>285.0</ResterendEigenRisico>
			<Rekeningnummer>NL02SNSB0259876354</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="XB76DU">
				<VerzekeringType>CGZ-Basic</VerzekeringType>
				<EigenRisico>285.0</EigenRisico>
				<startDatum>31-02-2014</startDatum>
				<eindDatum>31-02-2015</eindDatum>
			</VerzekeringPolis>
		</VerzekeringPolissen>
		<Facturen/>
		<Behandelingen/>
		<Diagnoses/>
	</Client>

	<Client BSN="216489194">
		<ClientGegevens>
			<Naam>Lieke Gerreman</Naam>
			<Adres>Marco Pololaan 1</Adres>
			<Postcode>4562AG</Postcode>
			<Woonplaats>Hulst</Woonplaats>
