=== richardman1/Facturatiesysteem/FacturatieSysteem/XML/facturatieSysteem.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="facturatieSysteem">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="verzekeringsmaatschappij">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="naam"/>
							<xs:element type="xs:string" name="adres"/>
							<xs:element type="xs:string" name="postcode"/>
							<xs:element type="xs:string" name="woonplaats"/>
							<xs:element type="xs:integer" name="KVKNummer"/>
							<xs:element type="xs:integer" name="rekeningNummer"/>
							<xs:element name="verzekeringsTypes">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="verzekeringsType" maxOccurs="unbounded" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element type="xs:string" name="naam"/>
													<xs:element name="behandelCodes">
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:byte" name="behandelcode" maxOccurs="unbounded" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element type="xs:string" name="verplichtEigenRisico"/>
												</xs:sequence>
												<xs:attribute type="xs:byte" name="id" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== richardman1/Facturatiesysteem/FacturatieSysteem/XML/facturatieSysteem.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><facturatieSysteem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="facturatieSysteem.xsd">
	<verzekeringsmaatschappij maatschappijnr="001">
      <naam>CGZ Verzekeringen</naam>
      <adres>Oranjeboomstraat 112</adres>
      <postcode>3311AC</postcode>
      <woonplaats>Rotterdam</woonplaats>
      <KVKNummer>81546371</KVKNummer>
      <rekeningNummer>921386577</rekeningNummer>
	  <verzekeringsTypes>
	  	  <verzekeringsType typenr="001">
	         <naam>CGZ-Basic</naam>
	         <verplichtEigenRisico>200</verplichtEigenRisico>
	         <behandelCodes>
	            <behandelcode>004</behandelcode>
	            <behandelcode>005</behandelcode>
	            <behandelcode>007</behandelcode>
				<behandelcode>001</behandelcode>
				<behandelcode>002</behandelcode>
			</behandelCodes>
	      </verzekeringsType>
	      <verzekeringsType typenr="002">
	         <naam>CGZ-All-risk</naam>
	         <verplichtEigenRisico>285</verplichtEigenRisico>
	         <behandelCodes>
	            <behandelcode>004</behandelcode>
	            <behandelcode>005</behandelcode>
	            <behandelcode>006</behandelcode>
	            <behandelcode>007</behandelcode>
	            <behandelcode>008</behandelcode>
	            <behandelcode>009</behandelcode>
	            <behandelcode>010</behandelcode>
	         	<behandelcode>001</behandelcode>
					<behandelcode>002</behandelcode>
					<behandelcode>003</behandelcode>
				</behandelCodes>
	      </verzekeringsType>
		
			</verzekeringsTypes>    
   </verzekeringsmaatschappij>
</facturatieSysteem>
